# Generated by Django 5.1.3 on 2024-11-06 13:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_eventtype_facility_catering_concertandshow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertandshow',
            name='available_tickets_for_each_type',
        ),
        migrations.RemoveField(
            model_name='concertandshow',
            name='price_by_ticket',
        ),
        migrations.RemoveField(
            model_name='concertandshow',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='available_rooms_for_each_type',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price_by_room_type',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='available_tickets_for_each_type',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='price_by_seating',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='catering',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='catering',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='concertandshow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='concertandshow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventplanner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventplanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photographyvideography',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='photographyvideography',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sports',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sports',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventplanner',
            name='event_type',
            field=models.CharField(blank=True, choices=[('conference', 'Conference'), ('trade_show', 'Trade Show'), ('party', 'Party'), ('wedding', 'Wedding'), ('festival', 'Festival'), ('exhibition', 'Exhibition'), ('charity_event', 'Charity Event'), ('workshop', 'Workshop')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='event_type_compatibility',
            field=models.JSONField(blank=True, choices=[('conference', 'Conference'), ('trade_show', 'Trade Show'), ('party', 'Party'), ('wedding', 'Wedding'), ('festival', 'Festival'), ('exhibition', 'Exhibition')], null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='facilities',
            field=models.JSONField(blank=True, choices=[('wifi', 'WiFi'), ('parking', 'Parking'), ('restrooms', 'Restrooms'), ('audio_visual', 'Audio-Visual Equipment'), ('stage_lighting', 'Stage and Lighting'), ('lounge_area', 'Lounge Area')], null=True),
        ),
        migrations.CreateModel(
            name='ConcertTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_tickets', models.PositiveIntegerField()),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='services.concertandshow')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_rooms', models.PositiveIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='services.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='SportsTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_tickets', models.PositiveIntegerField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='services.sports')),
            ],
        ),
    ]
